name: Deploy image to ECR with IAM allowance
description: Deploys an image to an ECR repository 
inputs:
  ECR_REGION:
    description: region ECR is in
    required: true
  ECR_ACCOUNT_NUMBER:
    description: account number for ecr repository
    required: true
  IMG:
    description: image to push to ECR, this can be a matrix of tagged images
    required: true
  REPOSITORY:
    description: repository to publish the image to
    required: true
runs:
  using: composite
  steps:
    - name: Push to ECR
      shell: bash
      run: |-
        export ECR_REGION=${{ inputs.ECR_REGION }}
        export ECR_ACCOUNT_NUMBER=${{ inputs.ECR_ACCOUNT_NUMBER }}
        export IMG=${{ inputs.IMG }}
        export REPOSITORY=${{ inputs.REPOSITORY }}

        echo -e "using inputs:\n \
                ecr-region - ${ECR_REGION}\n \
                acc_num - ${ECR_ACCOUNT_NUMBER}\n \
                img - ${IMG}\n \
                repo - ${REPOSITORY}"

        export ECR_URI=${ECR_ACCOUNT_NUMBER}.dkr.ecr.${ECR_REGION}.amazonaws.com
        echo "ecr uri - ${ECR_URI}"
        echo "Login to ECR"
        aws ecr get-login-password \
          --region ${ECR_REGION} \
          | docker login \
              --username AWS \
              --password-stdin ${ECR_URI}
        echo "Pushing ${IMG} to ECR with the ${ECR_URI}"
        set -x
        docker push ${ECR_URI}/${REPOSITORY}:${IMG}

